"""Add extend column to table games

Revision ID: 23339c9ca5c8
Revises: 6df3f8efd30d
Create Date: 2024-02-22 17:34:18.488163

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23339c9ca5c8"
down_revision: Union[str, None] = "6df3f8efd30d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column(
            "extend",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "extend")
    # ### end Alembic commands ###
