"""Added locale column to table users

Revision ID: ac604300df04
Revises: 23339c9ca5c8
Create Date: 2024-03-04 20:38:41.764677

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ac604300df04"
down_revision: Union[str, None] = "23339c9ca5c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "locale", sa.String(length=2), server_default="en", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "locale")
    # ### end Alembic commands ###
