"""Add is_allowed field to Game model

Revision ID: bc56c1ac4806
Revises: fc3fe72691d6
Create Date: 2024-02-18 12:37:49.442702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc56c1ac4806"
down_revision: Union[str, None] = "fc3fe72691d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column("is_allowed", sa.Boolean(), nullable=False),
    )
    op.drop_constraint("tg_id_unique", "users", type_="unique")
    op.drop_index("ix_users_tg_id", table_name="users")
    op.create_index(
        op.f("ix_users_tg_id"), "users", ["tg_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_tg_id"), table_name="users")
    op.create_index(
        "ix_users_tg_id", "users", ["tg_id"], unique=False
    )
    op.create_unique_constraint("tg_id_unique", "users", ["tg_id"])
    op.drop_column("games", "is_allowed")
    # ### end Alembic commands ###
