"""Added column locale to table games

Revision ID: cfa980cf6e62
Revises: ac604300df04
Create Date: 2024-03-07 11:33:12.165316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cfa980cf6e62"
down_revision: Union[str, None] = "ac604300df04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column(
            "locale", sa.String(length=2), server_default="en", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "locale")
    # ### end Alembic commands ###
